name: "CI"

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        apt update
        apt install -y meson libgranite-dev libgtk-3-dev libjson-glib-dev libgudev-1.0-dev libevdev-dev libgtksourceview-3.0-dev libxml2-dev libglib2.0-dev libgda-5.0-dev libmysqlclient-dev libpq-dev libgda-5.0-mysql libgda-5.0-postgres libsecret-1-dev libssh2-1-dev valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install
