name: "CI: Lint"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:

    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: io.elementary.vala-lint -d .
